"""Generate a compact C array from main/index.html for embedded builds."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
source = ROOT / "main" / "index.html"
target = ROOT / "main" / "index_html.h"
data = source.read_bytes() + b"\0"
lines = ["// Generated by tools/embed_html.py; edit index.html instead.",
         "#pragma once", "static const unsigned char index_html[] = {"]
for offset in range(0, len(data), 16):
    lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + 16]) + ",")
lines.append("};")
target.write_text("\n".join(lines) + "\n", encoding="ascii")
